package skill

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// agentsBeginMarker and agentsEndMarker bound the generated Intent section
// inside AGENTS.md so a reinstall can replace just that section, leaving the
// rest of a project's own AGENTS.md untouched.
const (
	agentsBeginMarker = "<!-- BEGIN INTENT SKILL (generated by `intent install-skill`; do not edit between markers) -->"
	agentsEndMarker   = "<!-- END INTENT SKILL -->"
)

// AGENTSAdapter emits (or updates) AGENTS.md for agent targets that read that
// convention instead of a Claude-style skill file. It carries the same shared
// Markdown body as ClaudeAdapter, with no YAML frontmatter.
type AGENTSAdapter struct{}

var _ Adapter = AGENTSAdapter{}

// Name identifies this adapter for the --agent agents-md flag value.
func (AGENTSAdapter) Name() string { return "agents-md" }

// Files returns the merged AGENTS.md content: the generated section replaces
// any prior generated section (found via the marker pair) in place, or is
// appended if AGENTS.md doesn't exist yet or has no prior generated section.
// It reads root to compute the merge but never writes — the caller installs
// the returned File.
func (AGENTSAdapter) Files(root string, c Content) ([]File, error) {
	section := agentsBeginMarker + "\n\n" + c.Markdown() + "\n" + agentsEndMarker + "\n"

	existing, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return []File{{Path: "AGENTS.md", Content: []byte(section)}}, nil
		}
		return nil, err
	}

	merged := mergeAgentsSection(string(existing), section)
	return []File{{Path: "AGENTS.md", Content: []byte(merged)}}, nil
}

// mergeAgentsSection replaces the marker-bounded generated section in body
// with section, or appends section (after a blank-line separator) if body
// carries no complete marker pair.
func mergeAgentsSection(body, section string) string {
	begin := strings.Index(body, agentsBeginMarker)
	if begin < 0 {
		return appendSection(body, section)
	}
	end := strings.Index(body[begin:], agentsEndMarker)
	if end < 0 {
		return appendSection(body, section)
	}
	end += begin + len(agentsEndMarker)
	// Consume one trailing newline after the end marker, if present, so
	// re-merging doesn't accumulate blank lines.
	if end < len(body) && body[end] == '\n' {
		end++
	}
	return body[:begin] + section + body[end:]
}

// appendSection adds section to the end of body, separated by a blank line.
// body may be empty (no prior AGENTS.md content).
func appendSection(body, section string) string {
	body = strings.TrimRight(body, "\n")
	if body == "" {
		return section
	}
	return body + "\n\n" + section
}
