package skill

import (
	"strings"

	"github.com/colchuck-ai/intent/internal/help"
)

// JudgmentPointer is one judgment distinction's one-line test, plus the slug
// to load for the full question/good/bad/failure-mode deep dive.
type JudgmentPointer struct {
	Slug    string
	Summary string
}

// Content is the shared, agent-agnostic skill payload (DESIGN §12): a
// trigger description, one paragraph on what Intent is, the entry-point
// instruction, 2-3 must-know gotchas, and a judgment pointer per distinction.
// It never embeds full judgment topic bodies — Markdown points at the slug
// so a reader (or agent) pulls the deep dive on demand via `intent help`.
type Content struct {
	Description string
	Intent      string
	EntryPoint  string
	Gotchas     []string
	Judgments   []JudgmentPointer
}

const (
	description = "Use when creating, editing, tracing, placing, or reviewing product or " +
		"engineering intent documents under `docs/product/` or `docs/engineering/` — " +
		"jobs-to-be-done, outcomes, risks, requirements, architecture, components, and their " +
		"Change Records (CR), Product Decision Records (PDR), and Architectural Decision " +
		"Records (ADR). Fire even when the user doesn't name the framework, but only for " +
		"intent-tree work. Skip for code changes, READMEs, marketing copy, or ad-hoc notes " +
		"that don't link into the intent tree."

	intentParagraph = "Intent keeps product and engineering intent — jobs, outcomes, risks, " +
		"requirements, architecture, components, and their decision and change records — in " +
		"one schema'd `intent.yaml`, read and written through the `intent` CLI. Intent is " +
		"declared explicitly; only its mechanical duals (backlinks, generated docs, maps) are " +
		"derived."

	entryPoint = "Drive the tree through the `intent` CLI, not by hand-editing files. Run " +
		"`intent help` for the full command and topic index. `intent.yaml` is the canonical " +
		"source; the rendered docs under `docs/` are generated — never hand-edit them."
)

// gotchas are the 2-3 must-know traps for the thin generated skill itself.
// They intentionally do not duplicate ref:* or judgment:* bodies — those are
// a slug lookup away — so this list only grows for a trap that isn't already
// one `intent help` call away.
var gotchas = []string{
	"Installed skill files (this one included) are generated by `intent install-skill` — " +
		"never hand-edit them; change the embedded help content and reinstall.",
	"This file carries only the one-line judgment test per distinction; run " +
		"`intent help judgment:<slug>` before drafting or reviewing for the full good/bad " +
		"pairs and failure mode.",
	"The full command, field, and error reference lives in `intent help ref:*` and " +
		"`intent help E0NN` — not duplicated here.",
}

// Render assembles the shared skill Content from embedded help. Judgment
// pointers come from help.InPlane("judgment"), which is already sorted by
// slug, so output order is deterministic across calls and builds.
func Render() Content {
	topics := help.InPlane("judgment")
	judgments := make([]JudgmentPointer, 0, len(topics))
	for _, t := range topics {
		judgments = append(judgments, JudgmentPointer{Slug: t.Slug, Summary: t.Summary})
	}
	return Content{
		Description: description,
		Intent:      intentParagraph,
		EntryPoint:  entryPoint,
		Gotchas:     append([]string(nil), gotchas...),
		Judgments:   judgments,
	}
}

// Markdown renders the agent-agnostic body shared by every Adapter: the
// Intent paragraph, entry point, gotchas, and judgment pointers. It excludes
// Description, which only Claude-style frontmatter uses for triggering —
// Adapters place it where their target format expects it.
func (c Content) Markdown() string {
	var b strings.Builder
	b.WriteString("# Intent\n\n")
	b.WriteString(c.Intent)
	b.WriteString("\n\n## Entry point\n\n")
	b.WriteString(c.EntryPoint)
	b.WriteString("\n\n## Gotchas\n\n")
	for _, g := range c.Gotchas {
		b.WriteString("- ")
		b.WriteString(g)
		b.WriteString("\n")
	}
	b.WriteString("\n## Judgment\n\n")
	for _, j := range c.Judgments {
		b.WriteString("- ")
		b.WriteString(j.Summary)
		b.WriteString(" — `intent help ")
		b.WriteString(j.Slug)
		b.WriteString("`\n")
	}
	return b.String()
}
