package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// snapshot reads every file under dir into a path->content map.
func snapshot(t *testing.T, dir string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(dir, p)
		out[filepath.ToSlash(rel)] = string(b)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// changedPaths returns the paths whose content differs between two snapshots
// (added, removed, or modified).
func changedPaths(before, after map[string]string) []string {
	var out []string
	for p, a := range after {
		if before[p] != a {
			out = append(out, p)
		}
	}
	for p := range before {
		if _, ok := after[p]; !ok {
			out = append(out, p)
		}
	}
	return out
}

func TestBuildThenCheckIsGreenAndDeterministic(t *testing.T) {
	dir := t.TempDir()
	out, err := run(t, "build", "-f", seedFlag, "--out", dir)
	if err != nil {
		t.Fatalf("build: %v\n%s", err, out)
	}
	if !strings.Contains(out, "wrote 8 page(s)") {
		t.Errorf("unexpected build output:\n%s", out)
	}

	first := snapshot(t, dir)

	out, err = run(t, "check", "-f", seedFlag, "--out", dir)
	if err != nil {
		t.Fatalf("check should be green after build: %v\n%s", err, out)
	}
	if !strings.Contains(out, "ok — docs match") {
		t.Errorf("expected green check:\n%s", out)
	}

	if _, err := run(t, "build", "-f", seedFlag, "--out", dir); err != nil {
		t.Fatalf("re-build: %v", err)
	}
	if diff := changedPaths(first, snapshot(t, dir)); len(diff) != 0 {
		t.Errorf("re-build was not byte-identical, changed: %v", diff)
	}
}

func TestCheckReportsMissingBeforeBuild(t *testing.T) {
	out, err := run(t, "check", "-f", seedFlag, "--out", t.TempDir())
	if err == nil {
		t.Fatalf("check should be nonzero when docs are absent\n%s", out)
	}
	if !strings.Contains(out, "drifted") || !strings.Contains(out, "missing") {
		t.Errorf("expected missing-page drift report:\n%s", out)
	}
}

func TestBuildRefusesInvalidTree(t *testing.T) {
	dir := t.TempDir()
	out, err := run(t, "build", "-f", "../validate/testdata/e001_edge.intent.yaml", "--out", dir)
	if err == nil {
		t.Fatalf("build should refuse an invalid tree\n%s", out)
	}
	if !strings.Contains(out, "E001") || !strings.Contains(out, "cannot build") {
		t.Errorf("expected a validation refusal citing E001:\n%s", out)
	}
	if len(snapshot(t, dir)) != 0 {
		t.Errorf("no pages should be written for an invalid tree")
	}
}

func TestBuildRemovesStalePagesButKeepsForeignFiles(t *testing.T) {
	dir := t.TempDir()
	if _, err := run(t, "build", "-f", seedFlag, "--out", dir); err != nil {
		t.Fatal(err)
	}

	// A generated page the tree no longer produces (has the banner).
	stale := filepath.Join(dir, "product", "orphan.md")
	writeFile(t, stale, "<!-- generated by intent from intent.yaml — do not edit -->\n# Orphan\n")
	// A file the tool didn't author (no banner) must be left alone.
	foreign := filepath.Join(dir, "product", "NOTES.md")
	writeFile(t, foreign, "hand-written notes\n")

	out, err := run(t, "build", "-f", seedFlag, "--out", dir)
	if err != nil {
		t.Fatalf("build: %v\n%s", err, out)
	}
	if !strings.Contains(out, "removed 1 stale page(s)") {
		t.Errorf("expected stale-removal report:\n%s", out)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale generated page should have been removed")
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Errorf("foreign file should be left untouched: %v", err)
	}
}

// TestAddingOneReferenceTouchesOnlyInvolvedPages is the locality guarantee: a
// single new edge changes exactly the referencing page and the referenced page.
func TestAddingOneReferenceTouchesOnlyInvolvedPages(t *testing.T) {
	dir := t.TempDir()
	if _, err := run(t, "build", "-f", "testdata/locality_base.intent.yaml", "--out", dir); err != nil {
		t.Fatal(err)
	}
	before := snapshot(t, dir)

	// locality_plus adds one relationships edge from comp_b to comp_a.
	if _, err := run(t, "build", "-f", "testdata/locality_plus.intent.yaml", "--out", dir); err != nil {
		t.Fatal(err)
	}
	changed := changedPaths(before, snapshot(t, dir))

	want := map[string]bool{
		"engineering/comp_b.md": true, // the new outgoing edge
		"engineering/comp_a.md": true, // the new incoming backlink
	}
	if len(changed) != len(want) {
		t.Fatalf("expected exactly %d pages to change, got %v", len(want), changed)
	}
	for _, p := range changed {
		if !want[p] {
			t.Errorf("unexpected page changed: %s", p)
		}
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
